# Generated by Django 2.1.7 on 2019-05-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='date_from',
        ),
        migrations.AddField(
            model_name='event',
            name='date_to',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
